# This is a basic workflow to help you get started with Actions

name: Link Validate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Find files with links
        shell: bash
        run: |
          echo 'FILES_TO_CHECK<<EOF' >> $GITHUB_ENV
          
          files_to_check=$(find $GITHUB_WORKSPACE -type f \
          -not -path '*/\.git/*' -not -path '*/\.github/*' -not -path '*/\node_modules/*'\
          -not -name "*.md")
          
          
          echo $files_to_check >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Validate that links are up
        uses: simeg/urlsup-action@v1.0.0
        with:
          args: ${{ env.FILES_TO_CHECK }} --threads 10 --allow 429 --white-list https://github.com/hippyaki/ESP32-Rest-Server/
